services:
  db:
    image: postgres:16
    container_name: habit-tracker-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: habit_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
